# Generated by Django 4.0.3 on 2022-06-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0002_category_name_en_us_category_name_ru_post_text_en_us_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='category_name', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en_us',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
    ]
