# Generated by Django 4.0.3 on 2022-06-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0003_alter_category_name_alter_category_name_en_us_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_en_us',
            new_name='name_af',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text_en_us',
            new_name='text_af',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title_en_us',
            new_name='title_af',
        ),
        migrations.AddField(
            model_name='category',
            name='name_ar',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ar_dz',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ast',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_az',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_be',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_bg',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_bn',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_br',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_bs',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ca',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_cs',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_cy',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_da',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_de',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_dsb',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_el',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en_au',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en_gb',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_eo',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es_ar',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es_co',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es_mx',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es_ni',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es_ve',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_et',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_eu',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fa',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fi',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fr',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fy',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ga',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_gd',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_gl',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_he',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_hi',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_hr',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_hsb',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_hu',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_hy',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ia',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ig',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ind',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_io',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_is',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_it',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ja',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ka',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_kab',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_kk',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_km',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_kn',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ko',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ky',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_lb',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_lt',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_lv',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_mk',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ml',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_mn',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_mr',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ms',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_my',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_nb',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ne',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_nl',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_nn',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_os',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_pa',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_pl',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_pt',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_pt_br',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ro',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_sk',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_sl',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_sq',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_sr',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_sr_latn',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_sv',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_sw',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ta',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_te',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_tg',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_th',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_tk',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_tr',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_tt',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_udm',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uk',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ur',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_vi',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_zh_hans',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_zh_hant',
            field=models.CharField(help_text='category_name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_ar_dz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_ast',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_be',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_bg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_bn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_br',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_bs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_ca',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_cs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_cy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_da',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_dsb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_el',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_en_au',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_en_gb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_eo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_es_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_es_co',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_es_mx',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_es_ni',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_es_ve',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_et',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_eu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_fa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_fi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_fy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_ga',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_gd',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_gl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_he',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_hi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_hr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_hsb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_hu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_hy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_ia',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_ig',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_ind',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_io',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_is',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_ja',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_ka',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_kab',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_kk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_km',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_kn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_ko',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_lb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_lt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_lv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_mk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_ml',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_mn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_mr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_ms',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_my',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_nb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_ne',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_nl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_nn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_os',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_pa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_pt_br',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_ro',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_sk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_sl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_sq',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_sr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_sr_latn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_sv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_sw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_ta',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_te',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_tg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_th',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_tk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_tt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_udm',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_ur',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_vi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_zh_hans',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_zh_hant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ar_dz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ast',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_be',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_bg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_br',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_bs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ca',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_cs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_cy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_da',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_dsb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_el',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en_au',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en_gb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_eo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_es_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_es_co',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_es_mx',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_es_ni',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_es_ve',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_et',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_eu',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_fa',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_fi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_fy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ga',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_gd',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_gl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_he',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_hi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_hr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_hsb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_hu',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_hy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ia',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ig',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ind',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_io',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_is',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_it',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ja',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ka',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_kab',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_kk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_km',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_kn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ky',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_lb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_lt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_lv',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_mk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ml',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_mn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_mr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ms',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_my',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_nb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ne',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_nl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_nn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_os',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_pa',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_pt_br',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ro',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_sk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_sl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_sq',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_sr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_sr_latn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_sv',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_sw',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ta',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_te',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_tg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_th',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_tk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_tt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_udm',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ur',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_vi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_zh_hans',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_zh_hant',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
