# Generated by Django 4.0.3 on 2022-06-06 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0005_rename_name_af_category_name_en_us_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kinds', to='simpleapp.category', verbose_name='This is the help text'),
        ),
    ]
